"""
Shared Pydantic models for Network Alerts.
Used by: Alert Engine, AI Agent, Action Executor, API Gateway
"""
import json
import uuid
from enum import Enum
from typing import Optional
from datetime import datetime
from pydantic import BaseModel, Field


class AlertType(str, Enum):
    """Types of network anomalies that can be detected."""
    HIGH_LATENCY = "HIGH_LATENCY"
    PACKET_LOSS = "PACKET_LOSS"
    DEVICE_DOWN = "DEVICE_DOWN"
    HIGH_CPU = "HIGH_CPU"
    HIGH_MEMORY = "HIGH_MEMORY"
    HIGH_INTERFACE_ERRORS = "HIGH_INTERFACE_ERRORS"
    BANDWIDTH_SATURATION = "BANDWIDTH_SATURATION"


class Severity(str, Enum):
    """
    Alert severity levels — determines urgency of response.
    INFO: Log only
    WARNING: Monitor closely
    CRITICAL: AI agent investigates, creates Jira ticket
    EMERGENCY: Immediate response, escalate oncall
    """
    INFO = "INFO"
    WARNING = "WARNING"
    CRITICAL = "CRITICAL"
    EMERGENCY = "EMERGENCY"


class AlertStatus(str, Enum):
    """Lifecycle status of an alert."""
    OPEN = "OPEN"                   # Just created, not yet handled
    INVESTIGATING = "INVESTIGATING"  # AI Agent is analyzing
    RESOLVED = "RESOLVED"           # Issue fixed
    FALSE_POSITIVE = "FALSE_POSITIVE"  # AI determined it was not a real issue


class Alert(BaseModel):
    """
    A network anomaly alert generated by the Alert Engine.
    Published to Kafka 'network.alerts' topic.
    Cached in Redis for fast lookups by AI Agent.
    """
    alert_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    device_id: str
    alert_type: AlertType
    severity: Severity
    threshold_breached: str = Field(..., description="Human readable threshold e.g. 'latency > 300ms (actual: 450ms)'")
    metric_value: float = Field(..., description="Actual value that breached the threshold")
    threshold_value: float = Field(..., description="Threshold value that was breached")
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    status: AlertStatus = Field(default=AlertStatus.OPEN)
    jira_ticket_id: Optional[str] = None
    root_cause: Optional[str] = None  # Filled in by AI Agent

    class Config:
        use_enum_values = True

    def to_kafka_payload(self) -> str:
        """Serialize to JSON string for Kafka message value."""
        data = self.dict()
        data["timestamp"] = self.timestamp.isoformat()
        return json.dumps(data)

    @classmethod
    def from_kafka_payload(cls, payload: str) -> "Alert":
        """Deserialize from Kafka message value."""
        data = json.loads(payload)
        return cls(**data)

    def to_redis_hash(self) -> dict:
        """Serialize for Redis HSET storage."""
        return {
            "alert_id": self.alert_id,
            "device_id": self.device_id,
            "alert_type": self.alert_type,
            "severity": self.severity,
            "threshold_breached": self.threshold_breached,
            "metric_value": str(self.metric_value),
            "threshold_value": str(self.threshold_value),
            "timestamp": self.timestamp.isoformat(),
            "status": self.status,
            "jira_ticket_id": self.jira_ticket_id or "",
            "root_cause": self.root_cause or "",
        }

    @classmethod
    def from_redis_hash(cls, data: dict) -> "Alert":
        """Deserialize from Redis HGETALL response."""
        return cls(
            alert_id=data["alert_id"],
            device_id=data["device_id"],
            alert_type=data["alert_type"],
            severity=data["severity"],
            threshold_breached=data["threshold_breached"],
            metric_value=float(data["metric_value"]),
            threshold_value=float(data["threshold_value"]),
            timestamp=datetime.fromisoformat(data["timestamp"]),
            status=data["status"],
            jira_ticket_id=data.get("jira_ticket_id") or None,
            root_cause=data.get("root_cause") or None,
        )
